[package]

name = "rustorm"
version = "0.0.1"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]

[lib]
name = "rustorm"

[[bin]]
name = "app_rustorm"


[dependencies]
rustc-serialize = "*"
postgres = "*"
uuid = "*"
log = "*"
env_logger = "*"
chrono = "*"
regex = "*"
