[package]
name = "rustorm"
version = "0.0.4"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A simple ORM and code generator for rust"
readme = "README.md"
repository = "https://github.com/ivanceras/rustorm"
documentation = "http://ivanceras.github.io/rustorm/rustorm/"

[lib]
name = "rustorm"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[dependencies.postgres]
version = "*"
features = ["time", "uuid", "chrono"]

[dependencies]
rustc-serialize = "*"
uuid = "*"
log = "*"
env_logger = "*"
regex = "*"
url = "*"

