[package]

name = "rustorm"
version = "0.0.1"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A simple ORM for rust"
readme = "README.md"
repository = "https://github.com/ivanceras/rustorm"
documentation = "http://ivanceras.github.io/rustorm/rustorm/"

[lib]
name = "rustorm"


[dependencies]
rustc-serialize = "*"
postgres = "*"
uuid = "*"
log = "*"
env_logger = "*"
chrono = "*"
regex = "*"
